id: P688F7B80
initial_creation_type: input
source_metadata:
  title: Drakkar Lobzang Palden
  language: en
  description: 'Texts by and about Drakkar Lobzang Palden Tendzin Nyendrak (blo bzang
    dpal ldan bstan ''dzin snyan grags, 1866–1929):'
  volume:
    50148ca9a69945f3baaa23697c5e58e0:
      title: Brief Biography of Drakkar Lobzang Palden
      parent: Biography
created_at: '2022-02-28T23:03:24.783790'
last_modified_at: '2022-02-28T23:03:24.783798'
